### ISSUE TITLE
uncaught exception

### ISSUE THREAD

**Issue by ajstri** [ajstri/ajstribot-v2#2]
[20:14:06] [Fatal] [JDA]: One of the EventListeners had an uncaught exception
[20:14:06] [Fatal] [JDA]: Encountered an exception:
[20:14:06] [Fatal] [JDA]: java.lang.NullPointerException
	at ajstri.commands.fun.GiggleCommand.execute(GiggleCommand.java:13)
	at ajstri.commands.CommandExecutor.onMessageReceived(CommandExecutor.java:24)
	at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:327)
	at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:64)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleDefaultMessage(MessageCreateHandler.java:129)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:51)
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:38)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:688)
	at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:437)
	at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:262)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:240)
	at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:965)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:748)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:110)
	at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:66)

**Comment by ajstri** [comment]
does not just happen with /giggle
occurs for all in dm
but what does this mean though
XD

**Comment by ajstri** [comment]
added in phase 2 but may remove -

**Comment by ajstri** [comment]
use userutils you nerd lol.

**Comment by ajstri** [comment]
updated onMessageReceived to onGuildMessageReceived in Command.java and CommandExecutor.java and the exception is no longer thrown
