### ISSUE TITLE
/help + category broken

### ISSUE THREAD

**Issue by ajstri** [ajstri/ajstribot-v2#6]
[19:14:25] [Fatal] [JDA]: One of the EventListeners had an uncaught exception
[19:14:25] [Fatal] [JDA]: Encountered an exception:
[19:14:25] [Fatal] [JDA]: java.lang.NullPointerException
	at ajstri.commands.generic.HelpCommand.execute(HelpCommand.java:35)
	at ajstri.commands.CommandExecutor.onGuildMessageReceived(CommandExecutor.java:25)
	at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:307)
	at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:64)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleDefaultMessage(MessageCreateHandler.java:101)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:51)
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:38)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:688)
	at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:437)
	at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:262)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:240)
	at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:965)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:748)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:110)
	at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:66)

**Comment by ajstri** [comment]
one of the categories was null - made it to the appropriate cat and updated -
